version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coinbase-backend
    ports:
      - "8001:8001"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    image: node:18-alpine
    container_name: coinbase-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    restart: always