version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8001 wsgi:app
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    environment:
      - FLASK_ENV=production
